name: flutter_contacts_plus_example
description: Demonstrates how to use the flutter_contacts_plus plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.2.0
  flutter_contacts_plus:
    path: ../
  image_picker: ^1.1.2
  pretty_json: ^2.0.0
  prompt_dialog: ^1.0.16

flutter:
  uses-material-design: true
